### ISSUE TITLE
Better solution for multiple fuel-core error

### ISSUE THREAD

**Issue by SilentCicero** [FuelLabs/fuels-rs#1023]
This error is clear, but I think the SDK should provide more help as to how the right way to resolve this should be or documentation as to how to resolve it.

i.e. here is what is wrong, here is how you can resolve it.

```sh
found more than one 'fuel-core' binary in PATH, using '/Users/nick/.fuelup/bin/fuel-core'
thread 'tokio-runtime-worker' panicked at 'error: Could not connect to fuel core server.', /Users/nick/.cargo/registry/src/github.com-1ecc6299db9ec823/fuels-test-helpers-0.43.0/src/node.rs:335:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError(())', /Users/nick/.cargo/registry/src/github.com-1ecc6299db9ec823/fuels-test-helpers-0.43.0/src/node.rs:320:14
```

**Comment by segfault-magnet** [comment]
@SilentCicero "found more than one `fuel-core`" doesn't cause an error. It is a warning message (should probably be moved to a log instead of being in `stderr`) introduced after we wasted a couple of hours debugging with the wrong `fuel-core` binary. It is there mainly to inform the user as to which binary was chosen.

The real error is that we couldn't connect to the node. And there we should have some more info surrounding why (presumably) the node closed unexpectedly.
