### ISSUE TITLE
Error making HTTP request

### ISSUE THREAD

**Issue by SwayStar123** [FuelLabs/fuels-rs#1387]
Reproduction: https://github.com/SwayStar123/testing_proj

Error
```---- test_proxy stdout ----
thread 'test_proxy' panicked at tests/harness.rs:77:10:
called `Result::unwrap()` on an `Err` value: Provider("io error: Error making HTTP request: error sending request for url (http://127.0.0.1:34031/v1/graphql): connection closed before message completed")

---- test_proxy2 stdout ----
thread '<unnamed>' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/fuel-vm-0.49.0/src/interpreter/blockchain.rs:650:18:
source slice length (8) does not match destination slice length (584)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/fuel-vm-0.49.0/src/interpreter/blockchain.rs:650:18:
source slice length (8) does not match destination slice length (584)
thread 'test_proxy2' panicked at tests/harness.rs:97:10:
called `Result::unwrap()` on an `Err` value: Provider("io error: Error making HTTP request: error sending request for url (http://127.0.0.1:35479/v1/graphql): connection closed before message completed")```

**Comment by Br1ght0ne** [comment]
Fixed in version `0.63` of the SDK. Verified on the repro project.
