### ISSUE TITLE
SparkPerps: Function call panics with big price numbers

### ISSUE THREAD

**Issue by dcpp** [FuelLabs/fuels-rs#1392]
Steps to reproduce:
a. Clone https://github.com/compolabs/spark-perps.git
b. checkout https://github.com/compolabs/spark-perps/tree/fix-big-price branch
c. build contracts and env
d. run test by cmd: cargo test --package spark-perps --test integration_tests -- fulfill_orders_test::fulfill_orders_test --exact --show-output

See same output:
   Compiling spark-perps v0.1.0 (/Users/ddolinin/Projects/compolabs/spark-perps-1)
    Finished test [unoptimized + debuginfo] target(s) in 20.19s
     Running tests/harness.rs (target/debug/deps/integration_tests-2300a9a000db167c)

running 1 test
test fulfill_orders_test::fulfill_orders_test ... FAILED

successes:

successes:

failures:

---- fulfill_orders_test::fulfill_orders_test stdout ----

 ██████╗ ██████╗ ███╗   ███╗██████╗  ██████╗ ███████╗ █████╗ ██████╗ ██╗██╗     ██╗████████╗██╗   ██╗
██╔════╝██╔═══██╗████╗ ████║██╔══██╗██╔═══██╗██╔════╝██╔══██╗██╔══██╗██║██║     ██║╚══██╔══╝╚██╗ ██╔╝
██║     ██║   ██║██╔████╔██║██████╔╝██║   ██║███████╗███████║██████╔╝██║██║     ██║   ██║    ╚████╔╝ 
██║     ██║   ██║██║╚██╔╝██║██╔═══╝ ██║   ██║╚════██║██╔══██║██╔══██╗██║██║     ██║   ██║     ╚██╔╝  
╚██████╗╚██████╔╝██║ ╚═╝ ██║██║     ╚██████╔╝███████║██║  ██║██████╔╝██║███████╗██║   ██║      ██║   
 ╚═════╝ ╚═════╝ ╚═╝     ╚═╝╚═╝      ╚═════╝ ╚══════╝╚═╝  ╚═╝╚═════╝ ╚═╝╚══════╝╚═╝   ╚═╝      ╚═╝   
                                                                                                     
██╗      █████╗ ██████╗ ███████╗                                                                     
██║     ██╔══██╗██╔══██╗██╔════╝                                                                     
██║     ███████║██████╔╝███████╗                                                                     
██║     ██╔══██║██╔══██╗╚════██║                                                                     
███████╗██║  ██║██████╔╝███████║                                                                     
╚══════╝╚═╝  ╚═╝╚═════╝ ╚══════╝                                                                     
                                                                                                     
🏁 Fulfill orders test 🏁 

admin_address = 09c0b2d1a486c439a87bcba6b46a7a1a23f3897cc83a94521a96da5c23bc58db
bob_address = bdaad6a89e073e177895b3e5a9ccd15806749eda134a6438dae32fc5b6601f3f
chad_address = 95a7aa6cc32743f8706c40ef49a7423b47da763bb4bbc055b1f07254dc729036

🔮 TEST ETH PRICE 203313000000
🔮 TEST USDC PRICE 1
🔮 TEST BTC PRICE 3754119461000

==================== Step #1 ====================
📜 Contract: vault
🤙 Function: deposit_collateral
👛 Wallet:   Bob
💰 Amount:   Amount: 1500.00 USDC

❌ clearing_house.get_market(0000000000000000000000000000000000000000000000000000000000000000)
❌ clearing_house.get_market(00db613343e17985e16e1204d2ad50f7c7203aef773433ced31c84210f524cbc)

    Markets state 🏪
     markets: ["ETH", "BTC"]
     treasury_owed_realized_pnl 0
     insurance_fund_owed_realized_pnl 0
     insurance_fund_capacity 0
     market_prices []
     mark_prices []
     last_fundings_growth_global [0, 0] 
     market_twaps []
     mark_twaps []
            

    Trader 🕺 Bob bdaad6a89e073e177895b3e5a9ccd15806749eda134a6438dae32fc5b6601f3f        
     clearing_house.all_pending_funding_payment: 0
     clearing_house.margin_requirement_for_liquidation: 0
     clearing_house.pending_funding_payment: funding_growth_globals: [] | funding_payments: []
     vault.get_account_value_and_total_collateral_value: (account_value: 1500000000, total_collateral_value: 1500000000)
     vault.get_free_collateral: 1500000000
     perp market.get_total_trader_order_bases: [0, 0]
     account_balance.owed_realized_pnl: 0, unrealized_pnl: 0
     account_balance.get_settlement_token_balance_and_unrealized_pnl: 1500000000
     account_balance.margin_requirement: 0
     account_balance.total_abs_position_value: 0
     account_balance.total_position_value: [0, 0]
     account_balance.account_balance: [
    (
        "asset: ETH (0000000000000000000000000000000000000000000000000000000000000000)",
        "taker_position_size: 0",
        "taker_open_notional: 0",
        "last_tw_premium_growth_global: 0",
    ),
    (
        "asset: BTC (00db613343e17985e16e1204d2ad50f7c7203aef773433ced31c84210f524cbc)",
        "taker_position_size: 0",
        "taker_open_notional: 0",
        "last_tw_premium_growth_global: 0",
    ),
]
     account_balance.all_trader_positions: []
            
⏰ timestamp + 600

==================== Step #2 ====================
📜 Contract: clearing house
🤙 Function: create_market
👛 Wallet:   Admin
💰 Amount:   name: BTC, im_ratio: 60000, mm_ratio: 50000

    Markets state 🏪
     markets: ["ETH", "BTC"]
     treasury_owed_realized_pnl 0
     insurance_fund_owed_realized_pnl 0
     insurance_fund_capacity 0
     market_prices [203313000000, 3754119461000]
     mark_prices [203313000000, 3754119461000]
     last_fundings_growth_global [0, 0] 
     market_twaps []
     mark_twaps [
    Twap {
        base_token: 0x0000000000000000000000000000000000000000000000000000000000000000,
        span: 3600,
        current_twap: 203313000000,
        last_update: 600,
    },
    Twap {
        base_token: 0x00db613343e17985e16e1204d2ad50f7c7203aef773433ced31c84210f524cbc,
        span: 3600,
        current_twap: 3754119461000,
        last_update: 600,
    },
]
            
⏰ timestamp + 600

==================== Step #3 ====================
📜 Contract: clearing house
🤙 Function: open_order
👛 Wallet:   Bob
💰 Amount:   LONG 0.5 BTC

account_value = I64 { value: 1500000000, negative: false }, total_collateral_value = I64 { value: 1500000000, negative: false }
margin requirement = 1126235838
thread 'fulfill_orders_test::fulfill_orders_test' panicked at tests/fulfill_orders_test.rs:191:72:
called `Result::unwrap()` on an `Err` value: RevertTransactionError { reason: "Panic", revert_id: 0, receipts: [Call { id: 0000000000000000000000000000000000000000000000000000000000000000, to: 8766ad35fae964b210016e7b4a0ed881c505ba85a75c2eea8c31339a6a887832, amount: 0, asset_id: 0000000000000000000000000000000000000000000000000000000000000000, gas: 9998785, param1: 3435052013, param2: 10448, pc: 12864, is: 12864 }, Call { id: 8766ad35fae964b210016e7b4a0ed881c505ba85a75c2eea8c31339a6a887832, to: 8f910b97e1d9fafe70d3cb4fc88b45d2609816a34bdb2c43bdd1015b9872ba45, amount: 0, asset_id: 0000000000000000000000000000000000000000000000000000000000000000, gas: 9998462, param1: 640754381, param2: 0, pc: 250384, is: 250384 }, ReturnData { id: 8f910b97e1d9fafe70d3cb4fc88b45d2609816a34bdb2c43bdd1015b9872ba45, ptr: 277600, len: 232, digest: 717a236055a6e9802f8928dcb24817dbe17b159850f4509eff0b1c032de6c398, pc: 269460, is: 250384, data: Some(0000000000000000f1d7a1ce6b...) }, Call { id: 8766ad35fae964b210016e7b4a0ed881c505ba85a75c2eea8c31339a6a887832, to: 8f910b97e1d9fafe70d3cb4fc88b45d2609816a34bdb2c43bdd1015b9872ba45, amount: 0, asset_id: 0000000000000000000000000000000000000000000000000000000000000000, gas: 9996854, param1: 640754381, param2: 0, pc: 250384, is: 250384 }, ReturnData { id: 8f910b97e1d9fafe70d3cb4fc88b45d2609816a34bdb2c43bdd1015b9872ba45, ptr: 277600, len: 232, digest: 717a236055a6e9802f8928dcb24817dbe17b159850f4509eff0b1c032de6c398, pc: 269460, is: 250384, data: Some(0000000000000000f1d7a1ce6b...) }, Call { id: 8766ad35fae964b210016e7b4a0ed881c505ba85a75c2eea8c31339a6a887832, to: f1d7a1ce6b6df8b7c52400a946c31a44ec09d30519030f8a900b2f08cd7cc2d0, amount: 0, asset_id: 0000000000000000000000000000000000000000000000000000000000000000, gas: 9991954, param1: 2675389920, param2: 248712, pc: 250384, is: 250384 }, Call { id: f1d7a1ce6b6df8b7c52400a946c31a44ec09d30519030f8a900b2f08cd7cc2d0, to: 8f910b97e1d9fafe70d3cb4fc88b45d2609816a34bdb2c43bdd1015b9872ba45, amount: 0, asset_id: 0000000000000000000000000000000000000000000000000000000000000000, gas: 9984283, param1: 640754381, param2: 0, pc: 530112, is: 530112 }, ReturnData { id: 8f910b97e1d9fafe70d3cb4fc88b45d2609816a34bdb2c43bdd1015b9872ba45, ptr: 557328, len: 232, digest: 717a236055a6e9802f8928dcb24817dbe17b159850f4509eff0b1c032de6c398, pc: 549188, is: 530112, data: Some(0000000000000000f1d7a1ce6b...) }, Call { id: f1d7a1ce6b6df8b7c52400a946c31a44ec09d30519030f8a900b2f08cd7cc2d0, to: 8f910b97e1d9fafe70d3cb4fc88b45d2609816a34bdb2c43bdd1015b9872ba45, amount: 0, asset_id: 0000000000000000000000000000000000000000000000000000000000000000, gas: 9981362, param1: 640754381, param2: 0, pc: 530112, is: 530112 }, ReturnData { id: 8f910b97e1d9fafe70d3cb4fc88b45d2609816a34bdb2c43bdd1015b9872ba45, ptr: 557328, len: 232, digest: 717a236055a6e9802f8928dcb24817dbe17b159850f4509eff0b1c032de6c398, pc: 549188, is: 530112, data: Some(0000000000000000f1d7a1ce6b...) }, Call { id: f1d7a1ce6b6df8b7c52400a946c31a44ec09d30519030f8a900b2f08cd7cc2d0, to: 5157541687c8cddb1118afb5a23655970003c59a0e0cab46930c8ab5e077a28d, amount: 0, asset_id: 0000000000000000000000000000000000000000000000000000000000000000, gas: 9979549, param1: 3417376219, param2: 526968, pc: 530112, is: 530112 }, ReturnData { id: 5157541687c8cddb1118afb5a23655970003c59a0e0cab46930c8ab5e077a28d, ptr: 600824, len: 144, digest: b7d3aa37d63f9948ae74939a3f90d7dc11b3d9cece8ee789a80659ef5bf27996, pc: 594984, is: 530112, data: Some(00db613343e17985e16e1204d2...) }, Call { id: f1d7a1ce6b6df8b7c52400a946c31a44ec09d30519030f8a900b2f08cd7cc2d0, to: 8f910b97e1d9fafe70d3cb4fc88b45d2609816a34bdb2c43bdd1015b9872ba45, amount: 0, asset_id: 0000000000000000000000000000000000000000000000000000000000000000, gas: 9977844, param1: 448081130, param2: 0, pc: 530112, is: 530112 }, Return { id: 8f910b97e1d9fafe70d3cb4fc88b45d2609816a34bdb2c43bdd1015b9872ba45, val: 1200, pc: 550864, is: 530112 }, Call { id: f1d7a1ce6b6df8b7c52400a946c31a44ec09d30519030f8a900b2f08cd7cc2d0, to: 245442ac953fe2b2eb1023f465fd2728dcfd039049652ee06f992313a9768e05, amount: 0, asset_id: 0000000000000000000000000000000000000000000000000000000000000000, gas: 9976741, param1: 902148450, param2: 527096, pc: 530112, is: 530112 }, Return { id: 245442ac953fe2b2eb1023f465fd2728dcfd039049652ee06f992313a9768e05, val: 3754119461000, pc: 656236, is: 530112 }, Call { id: f1d7a1ce6b6df8b7c52400a946c31a44ec09d30519030f8a900b2f08cd7cc2d0, to: 8f910b97e1d9fafe70d3cb4fc88b45d2609816a34bdb2c43bdd1015b9872ba45, amount: 0, asset_id: 0000000000000000000000000000000000000000000000000000000000000000, gas: 9975102, param1: 3538106852, param2: 527128, pc: 530112, is: 530112 }, Return { id: 8f910b97e1d9fafe70d3cb4fc88b45d2609816a34bdb2c43bdd1015b9872ba45, val: 3754119461000, pc: 547564, is: 530112 }, Call { id: f1d7a1ce6b6df8b7c52400a946c31a44ec09d30519030f8a900b2f08cd7cc2d0, to: 8f910b97e1d9fafe70d3cb4fc88b45d2609816a34bdb2c43bdd1015b9872ba45, amount: 0, asset_id: 0000000000000000000000000000000000000000000000000000000000000000, gas: 9972197, param1: 640754381, param2: 0, pc: 530112, is: 530112 }, ReturnData { id: 8f910b97e1d9fafe70d3cb4fc88b45d2609816a34bdb2c43bdd1015b9872ba45, ptr: 557328, len: 232, digest: 717a236055a6e9802f8928dcb24817dbe17b159850f4509eff0b1c032de6c398, pc: 549188, is: 530112, data: Some(0000000000000000f1d7a1ce6b...) }, Call { id: f1d7a1ce6b6df8b7c52400a946c31a44ec09d30519030f8a900b2f08cd7cc2d0, to: 5157541687c8cddb1118afb5a23655970003c59a0e0cab46930c8ab5e077a28d, amount: 0, asset_id: 0000000000000000000000000000000000000000000000000000000000000000, gas: 9970384, param1: 3417376219, param2: 527000, pc: 530112, is: 530112 }, ReturnData { id: 5157541687c8cddb1118afb5a23655970003c59a0e0cab46930c8ab5e077a28d, ptr: 600824, len: 144, digest: b7d3aa37d63f9948ae74939a3f90d7dc11b3d9cece8ee789a80659ef5bf27996, pc: 594984, is: 530112, data: Some(00db613343e17985e16e1204d2...) }, ReturnData { id: f1d7a1ce6b6df8b7c52400a946c31a44ec09d30519030f8a900b2f08cd7cc2d0, ptr: 511592, len: 32, digest: 9ac765193eef0c3ea3b827d94075cf34c261ddadef59a851850c7a26ba90ff1e, pc: 484004, is: 250384, data: Some(0000000059682f000000000000...) }, Call { id: 8766ad35fae964b210016e7b4a0ed881c505ba85a75c2eea8c31339a6a887832, to: f1d7a1ce6b6df8b7c52400a946c31a44ec09d30519030f8a900b2f08cd7cc2d0, amount: 0, asset_id: 0000000000000000000000000000000000000000000000000000000000000000, gas: 9957392, param1: 2481079295, param2: 10448, pc: 250384, is: 250384 }, Call { id: f1d7a1ce6b6df8b7c52400a946c31a44ec09d30519030f8a900b2f08cd7cc2d0, to: 8f910b97e1d9fafe70d3cb4fc88b45d2609816a34bdb2c43bdd1015b9872ba45, amount: 0, asset_id: 0000000000000000000000000000000000000000000000000000000000000000, gas: 9957022, param1: 640754381, param2: 0, pc: 519184, is: 519184 }, ReturnData { id: 8f910b97e1d9fafe70d3cb4fc88b45d2609816a34bdb2c43bdd1015b9872ba45, ptr: 546400, len: 232, digest: 717a236055a6e9802f8928dcb24817dbe17b159850f4509eff0b1c032de6c398, pc: 538260, is: 519184, data: Some(0000000000000000f1d7a1ce6b...) }, Call { id: f1d7a1ce6b6df8b7c52400a946c31a44ec09d30519030f8a900b2f08cd7cc2d0, to: 8f910b97e1d9fafe70d3cb4fc88b45d2609816a34bdb2c43bdd1015b9872ba45, amount: 0, asset_id: 0000000000000000000000000000000000000000000000000000000000000000, gas: 9953054, param1: 640754381, param2: 0, pc: 519184, is: 519184 }, ReturnData { id: 8f910b97e1d9fafe70d3cb4fc88b45d2609816a34bdb2c43bdd1015b9872ba45, ptr: 546400, len: 232, digest: 717a236055a6e9802f8928dcb24817dbe17b159850f4509eff0b1c032de6c398, pc: 538260, is: 519184, data: Some(0000000000000000f1d7a1ce6b...) }, Call { id: f1d7a1ce6b6df8b7c52400a946c31a44ec09d30519030f8a900b2f08cd7cc2d0, to: 5157541687c8cddb1118afb5a23655970003c59a0e0cab46930c8ab5e077a28d, amount: 0, asset_id: 0000000000000000000000000000000000000000000000000000000000000000, gas: 9951242, param1: 3417376219, param2: 517336, pc: 519184, is: 519184 }, ReturnData { id: 5157541687c8cddb1118afb5a23655970003c59a0e0cab46930c8ab5e077a28d, ptr: 589896, len: 144, digest: b7d3aa37d63f9948ae74939a3f90d7dc11b3d9cece8ee789a80659ef5bf27996, pc: 584056, is: 519184, data: Some(00db613343e17985e16e1204d2...) }, Call { id: f1d7a1ce6b6df8b7c52400a946c31a44ec09d30519030f8a900b2f08cd7cc2d0, to: 245442ac953fe2b2eb1023f465fd2728dcfd039049652ee06f992313a9768e05, amount: 0, asset_id: 0000000000000000000000000000000000000000000000000000000000000000, gas: 9946688, param1: 1126797681, param2: 517272, pc: 519184, is: 519184 }, ReturnData { id: 245442ac953fe2b2eb1023f465fd2728dcfd039049652ee06f992313a9768e05, ptr: 662384, len: 16, digest: 3d096c02f85f73c2e39216d49ff711d5ad3bcbd33629d13c758a9e52f6281b21, pc: 646052, is: 519184, data: Some(000000000007a12000fbe0047400052a) }, Call { id: f1d7a1ce6b6df8b7c52400a946c31a44ec09d30519030f8a900b2f08cd7cc2d0, to: 8f910b97e1d9fafe70d3cb4fc88b45d2609816a34bdb2c43bdd1015b9872ba45, amount: 0, asset_id: 0000000000000000000000000000000000000000000000000000000000000000, gas: 9944120, param1: 640754381, param2: 0, pc: 519184, is: 519184 }, ReturnData { id: 8f910b97e1d9fafe70d3cb4fc88b45d2609816a34bdb2c43bdd1015b9872ba45, ptr: 546400, len: 232, digest: 717a236055a6e9802f8928dcb24817dbe17b159850f4509eff0b1c032de6c398, pc: 538260, is: 519184, data: Some(0000000000000000f1d7a1ce6b...) }, Call { id: f1d7a1ce6b6df8b7c52400a946c31a44ec09d30519030f8a900b2f08cd7cc2d0, to: 5157541687c8cddb1118afb5a23655970003c59a0e0cab46930c8ab5e077a28d, amount: 0, asset_id: 0000000000000000000000000000000000000000000000000000000000000000, gas: 9942308, param1: 3417376219, param2: 517208, pc: 519184, is: 519184 }, ReturnData { id: 5157541687c8cddb1118afb5a23655970003c59a0e0cab46930c8ab5e077a28d, ptr: 589896, len: 144, digest: b7d3aa37d63f9948ae74939a3f90d7dc11b3d9cece8ee789a80659ef5bf27996, pc: 584056, is: 519184, data: Some(00db613343e17985e16e1204d2...) }, Call { id: f1d7a1ce6b6df8b7c52400a946c31a44ec09d30519030f8a900b2f08cd7cc2d0, to: 8f910b97e1d9fafe70d3cb4fc88b45d2609816a34bdb2c43bdd1015b9872ba45, amount: 0, asset_id: 0000000000000000000000000000000000000000000000000000000000000000, gas: 9940604, param1: 640754381, param2: 0, pc: 519184, is: 519184 }, ReturnData { id: 8f910b97e1d9fafe70d3cb4fc88b45d2609816a34bdb2c43bdd1015b9872ba45, ptr: 546400, len: 232, digest: 717a236055a6e9802f8928dcb24817dbe17b159850f4509eff0b1c032de6c398, pc: 538260, is: 519184, data: Some(0000000000000000f1d7a1ce6b...) }, Call { id: f1d7a1ce6b6df8b7c52400a946c31a44ec09d30519030f8a900b2f08cd7cc2d0, to: 245442ac953fe2b2eb1023f465fd2728dcfd039049652ee06f992313a9768e05, amount: 0, asset_id: 0000000000000000000000000000000000000000000000000000000000000000, gas: 9938442, param1: 3548110791, param2: 517176, pc: 519184, is: 519184 }, Call { id: 245442ac953fe2b2eb1023f465fd2728dcfd039049652ee06f992313a9768e05, to: 8f910b97e1d9fafe70d3cb4fc88b45d2609816a34bdb2c43bdd1015b9872ba45, amount: 0, asset_id: 0000000000000000000000000000000000000000000000000000000000000000, gas: 9935009, param1: 448081130, param2: 0, pc: 664992, is: 664992 }, Return { id: 8f910b97e1d9fafe70d3cb4fc88b45d2609816a34bdb2c43bdd1015b9872ba45, val: 1200, pc: 685744, is: 664992 }, Panic { id: 245442ac953fe2b2eb1023f465fd2728dcfd039049652ee06f992313a9768e05, reason: PanicInstruction { reason: OutOfGas, instruction: LW { dst: 0x10, addr: 0x3c, offset: 0 } (bytes: 5d 43 c0 00) }, pc: 654452, is: 519184, contract_id: None }, ScriptResult { result: Panic, gas_used: 10000000 }] }
stack backtrace:
   0: rust_begin_unwind
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:647:5
   1: core::panicking::panic_fmt
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/result.rs:1649:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/result.rs:1073:23
   4: integration_tests::fulfill_orders_test::fulfill_orders_test::{{closure}}
             at ./tests/fulfill_orders_test.rs:191:27
   5: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/future/future.rs:124:9
   6: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/future/future.rs:124:9
   7: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}::{{closure}}
             at /Users/ddolinin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/current_thread/mod.rs:659:57
   8: tokio::runtime::coop::with_budget
             at /Users/ddolinin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/coop.rs:107:5
   9: tokio::runtime::coop::budget
             at /Users/ddolinin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/coop.rs:73:5
  10: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}
             at /Users/ddolinin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/current_thread/mod.rs:659:25
  11: tokio::runtime::scheduler::current_thread::Context::enter
             at /Users/ddolinin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/current_thread/mod.rs:404:19
  12: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}
             at /Users/ddolinin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/current_thread/mod.rs:658:36
  13: tokio::runtime::scheduler::current_thread::CoreGuard::enter::{{closure}}
             at /Users/ddolinin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/current_thread/mod.rs:737:68
  14: tokio::runtime::context::scoped::Scoped<T>::set
             at /Users/ddolinin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/context/scoped.rs:40:9
  15: tokio::runtime::context::set_scheduler::{{closure}}
             at /Users/ddolinin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/context.rs:176:26
  16: std::thread::local::LocalKey<T>::try_with
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/thread/local.rs:286:16
  17: std::thread::local::LocalKey<T>::with
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/thread/local.rs:262:9
  18: tokio::runtime::context::set_scheduler
             at /Users/ddolinin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/context.rs:176:9
  19: tokio::runtime::scheduler::current_thread::CoreGuard::enter
             at /Users/ddolinin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/current_thread/mod.rs:737:27
  20: tokio::runtime::scheduler::current_thread::CoreGuard::block_on
             at /Users/ddolinin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/current_thread/mod.rs:646:19
  21: tokio::runtime::scheduler::current_thread::CurrentThread::block_on::{{closure}}
             at /Users/ddolinin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/current_thread/mod.rs:175:28
  22: tokio::runtime::context::runtime::enter_runtime
             at /Users/ddolinin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/context/runtime.rs:65:16
  23: tokio::runtime::scheduler::current_thread::CurrentThread::block_on
             at /Users/ddolinin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/current_thread/mod.rs:167:9
  24: tokio::runtime::runtime::Runtime::block_on
             at /Users/ddolinin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/runtime.rs:349:47
  25: integration_tests::fulfill_orders_test::fulfill_orders_test
             at ./tests/fulfill_orders_test.rs:273:5
  26: integration_tests::fulfill_orders_test::fulfill_orders_test::{{closure}}
             at ./tests/fulfill_orders_test.rs:19:31
  27: core::ops::function::FnOnce::call_once
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/ops/function.rs:250:5
  28: core::ops::function::FnOnce::call_once
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

failures:
    fulfill_orders_test::fulfill_orders_test

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 9 filtered out; finished in 59.97s

error: test failed, to rerun pass `-p spark-perps --test integration_tests`

**Comment by digorithm** [comment]
Hey @dcpp, sorry for the late reply. Are you still having this problem, or was it resolved somehow?
