### ISSUE TITLE
Overflow when setting CallParameters coins forwarded to `u64::MAX`

### ISSUE THREAD

**Issue by nfurfaro** [FuelLabs/fuels-rs#687]
Given the following contract:
```
contract;

abi TestContract {
    fn overflow(n: u64) -> u64;
}

impl TestContract for Contract {
    fn overflow(n: u64) -> u64 {
        n
    }
}
```

and this `harness.rs` :

```
use fuels::prelude::*;

abigen!(TestContract, "./out/debug/bug_repro-abi.json");

#[tokio::test]
// #[should_panic(expected = "ArithmeticOverflow")]
async fn overflows() {
    let wallet = launch_provider_and_get_wallet().await;
    let instance = get_test_instance(wallet).await;

    let test_params = CallParameters::new(Some(u64::MAX), None, None);

    instance
        .methods()
        .overflow(100u64)
        .call_params(test_params)
        .call()
        .await
        .unwrap();
}

async fn get_test_instance(wallet: WalletUnlocked) -> TestContract {
    let pow_id = Contract::deploy(
        "./out/debug/bug_repro.bin",
        &wallet,
        TxParameters::default(),
        StorageConfiguration::default(),
    )
    .await
    .unwrap();

    let instance = TestContract::new(pow_id.clone(), wallet);

    instance
}

```

When running the test, you'll get this error:
```
running 1 test
test overflows ... FAILED

failures:

---- overflows stdout ----
thread 'overflows' panicked at 'attempt to multiply with overflow', /Users/furnic/.cargo/registry/src/github.com-1ecc6299db9ec823/fuel-core-0.14.0/src/resource_query.rs:168:28
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'overflows' panicked at 'called `Result::unwrap()` on an `Err` value: ProviderError("connection closed")', test/harness.rs:17:10
```

**Comment by nfurfaro** [comment]
IMO, we should allow users to forward `u64::MAX` coins with a call.

**Comment by segfault-magnet** [comment]
[The panic happens in fuel-core](https://github.com/FuelLabs/fuel-core/blob/81cafe4a1e1e813d91fd116d2b1dfd5951d3e13c/fuel-core/src/resource_query.rs#L168) as part of the random_improve algorithm. When adding dust an upper limit is calculated as amount  * 2 causing the overflow.
An asset amount is u64 in fuel-core's API (resources_to_spend), so there's nothing clean we can do about it in the SDK. Bumping the amount down to a u32 seems like implementation details leakage into the sdk.
